/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NotificationsSlideover: typeof import('./resources/js/components/NotificationsSlideover.vue')['default']
    TextLink: typeof import('./resources/js/components/TextLink.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UChip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSearch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue')['default']
    UDashboardSearchButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UserMenu: typeof import('./resources/js/components/UserMenu.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@inertiajs+vue3@2.3.15_vue@3.5.28_typescript@5.9.3___@tiptap+extensions@_5eee9b2c541115b038d28e1f4318f55d/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
