name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # Added pnpm setup
        with:
          version: 8
          run_install: false # We'll run install manually

      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile # Changed from npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        run: pnpm run build # Changed from npm run build

      - name: Tests
        run: ./vendor/bin/phpunit
